---
- hosts: all
  become: true
  tasks:
  - name: Install useful packages 
    yum:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - epel-release
      - screen
      - curl
      - vim
      - wget
      - ca-certificates

  - name: Update Iptables Settings
    copy:
      dest: /etc/sysctl.d/k8s.conf
      content: | 
        net.bridge.bridge-nf-call-ip6tables = 1
        net.bridge.bridge-nf-call-iptables = 1

  - name: Run sysctl command
    command: sysctl --system

  - name: Set selinux setenforce to ZERO
    command: setenforce 0

  - name: Put SELinux in permissive mode in the configuration file
    lineinfile:
      path: /etc/selinux/config
      regexp: 'SELINUX=enforcing'
      line: 'SELINUX=permissive'

  - name: Add an yum signing key for Docker
    rpm_key:
      key: https://download.docker.com/linux/centos/gpg
      state: present

  - name: Add yum repository for stable version
    shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    args:
      creates: /etc/yum.repos.d/docker-ce.repo
    #yum_repository:
    #  name: docker
    #  repo: rpm [arch=amd64] https://download.docker.com/linux/centos/docker-ce.repo
    #  state: present

  - name: Install docker and its dependecies
    yum: 
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - docker-ce 
      - docker-ce-cli 
      - containerd.io
    notify:
      - docker status

  - name: Add vagrant user to docker group
    user:
      name: vagrant
      group: docker

  - name: Restart Docker service 
    service:
      name: docker
      daemon_reload: yes
      state: restarted

  - name: Enable Docker services
    service: 
      name: docker
      enabled: yes

  - name: Remove swapfile from /etc/fstab
    mount:
      name: "{{ item }}"
      fstype: swap
      state: absent
    with_items:
      - swap
      - none

  - name: Disable swap
    command: swapoff -a
    when: ansible_swaptotal_mb > 0

  - name: Add an yum signing key for Kubernetes
    rpm_key:
      key: https://packages.cloud.google.com/yum/doc/yum-key.gpg
      state: present

  - name: Adding yum repository for Kubernetes
    yum_repository:
      name: Kubernetes
      description: Kubernetes Centos7 Repo
      baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
      enabled: 1
      gpgcheck: 1
      repo_gpgcheck: 1
      gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

  - name: Install Kubernetes binaries
    yum: 
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
        - kubelet 
        - kubeadm 
        - kubectl

  - name: Configure node ip
    lineinfile:
      path: /etc/sysconfig/kubelet
      line: KUBELET_EXTRA_ARGS=--node-ip={{ node_ip }}

  - name: Restart kubelet
    service:
      name: kubelet
      daemon_reload: yes
      state: restarted

  - name: Enable kubelet services
    service: 
      name: kubelet
      enabled: yes

  - name: Copy the join command to server location
    copy: 
      src: join-command 
      dest: /tmp/join-command.sh 
      mode: 0777

  - name: Join the node to cluster
    command: sh /tmp/join-command.sh

  handlers:
    - name: docker status
      service: 
        name: docker 
        state: started
